/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scheduler;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import sun.java2d.pipe.hw.AccelDeviceEventNotifier;
import java.util.Arrays;

/**
 *
 * @author User
 */
public class IScheduler extends javax.swing.JFrame {



    /**
     * Creates new form IScheduler
     */
    public IScheduler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ENTER_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Deadline_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Capacity_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Period_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NEXT_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mytable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        SCHEDULE_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Seconds_field = new javax.swing.JTextField();
        Arrival_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ID_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_fieldActionPerformed(evt);
            }
        });
        ID_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ID_fieldKeyPressed(evt);
            }
        });

        jLabel1.setText("ID of the process:");

        ENTER_button.setBackground(new java.awt.Color(0, 0, 255));
        ENTER_button.setText("ENTER");
        ENTER_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTER_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Deadline:");

        Deadline_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deadline_fieldActionPerformed(evt);
            }
        });
        Deadline_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Deadline_fieldKeyPressed(evt);
            }
        });

        jLabel3.setText("Capacity:");

        Capacity_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Capacity_fieldKeyPressed(evt);
            }
        });

        jLabel4.setText("Period:");

        Period_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Period_fieldKeyPressed(evt);
            }
        });

        jLabel5.setText("Arrival time:");

        NEXT_button.setBackground(new java.awt.Color(51, 255, 0));
        NEXT_button.setText("NEXT PROCESS");
        NEXT_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXT_buttonActionPerformed(evt);
            }
        });

        mytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Deadline", "Capacity", "Period", "Arrival time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mytable);

        jLabel6.setText("EARLIEST DEADLINE FIRST SCHEDULER");

        SCHEDULE_button.setBackground(new java.awt.Color(255, 153, 0));
        SCHEDULE_button.setText("SCHEDULE");
        SCHEDULE_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCHEDULE_buttonActionPerformed(evt);
            }
        });

        jLabel7.setText("PRESS ENTER TO SAVE YOUR PROCESS");

        jLabel8.setText("PRESS NEXT PROCESS TO CLEAR TEXT");

        jLabel9.setText("NO OF SECONDS (MAX 20):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ID_field))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ENTER_button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NEXT_button))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Deadline_field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Capacity_field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Period_field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Arrival_field)))
                                .addGap(93, 93, 93)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(446, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SCHEDULE_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Seconds_field, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID_field))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Deadline_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Capacity_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Period_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Arrival_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ENTER_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NEXT_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Seconds_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SCHEDULE_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_fieldActionPerformed

    private void Deadline_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deadline_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Deadline_fieldActionPerformed

    private void ID_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ID_fieldKeyPressed
          if(evt.getKeyCode()==10){
       if(ID_field.getText().isEmpty()){
       
           JOptionPane.showMessageDialog(this,"please enter a valied ID number",
                   "Error massage",JOptionPane.ERROR_MESSAGE );
       }else{
              Deadline_field.grabFocus();
               }
       
       }
    }//GEN-LAST:event_ID_fieldKeyPressed

    private void Deadline_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Deadline_fieldKeyPressed
          if(evt.getKeyCode()==10){
       if(Deadline_field.getText().isEmpty()){
       
           JOptionPane.showMessageDialog(this,"please enter a valied ID number",
                   "Error massage",JOptionPane.ERROR_MESSAGE );
       }else{
              Capacity_field.grabFocus();
               }
       
       }
    }//GEN-LAST:event_Deadline_fieldKeyPressed

    private void Capacity_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Capacity_fieldKeyPressed
          if(evt.getKeyCode()==10){
       if(Capacity_field.getText().isEmpty()){
       
           JOptionPane.showMessageDialog(this,"please enter a valied ID number",
                   "Error massage",JOptionPane.ERROR_MESSAGE );
       }else{
              Period_field.grabFocus();
               }
       
       }
    }//GEN-LAST:event_Capacity_fieldKeyPressed

    private void Period_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Period_fieldKeyPressed
          if(evt.getKeyCode()==10){
       if(Period_field.getText().isEmpty()){
       
           JOptionPane.showMessageDialog(this,"please enter a valied ID number",
                   "Error massage",JOptionPane.ERROR_MESSAGE );
       }else{
              Arrival_field.grabFocus();
               }
       
       }
    }//GEN-LAST:event_Period_fieldKeyPressed

    static ArrayList <Details> data_base=new ArrayList();
    static Time_keeper tk ;
    
    private void ENTER_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTER_buttonActionPerformed
        if(ID_field.getText().isEmpty()){
     JOptionPane.showMessageDialog(this,"please enter a valied ID number",
                   "Error massage",JOptionPane.ERROR_MESSAGE );

}else if(Capacity_field.getText().isEmpty()){
     JOptionPane.showMessageDialog(this,"Name filed cannot be empty",
                    "Error Massage",JOptionPane.ERROR_MESSAGE );
            
} else if(Deadline_field.getText().isEmpty()){
     JOptionPane.showMessageDialog(this,"Name filed cannot be empty",
                    "Error Massage",JOptionPane.ERROR_MESSAGE );

} else if(Period_field.getText().isEmpty()){
     JOptionPane.showMessageDialog(this,"Name filed cannot be empty",
                    "Error Massage",JOptionPane.ERROR_MESSAGE );

}else if(Arrival_field.getText().isEmpty()){
     JOptionPane.showMessageDialog(this,"Name filed cannot be empty",
                    "Error Massage",JOptionPane.ERROR_MESSAGE );

}else{ 
        
    
Details d=new Details();
d.setId(ID_field.getText());
d.setDeadline(Integer.valueOf(Deadline_field.getText())+Integer.valueOf(Arrival_field.getText()));
d.setArrival_time(Integer.valueOf(Arrival_field.getText()));
d.setCapacity(Integer.valueOf(Capacity_field.getText()));
d.setPeriod(Integer.valueOf(Period_field.getText()));


data_base.add(d);


DefaultTableModel dtm=(DefaultTableModel)mytable.getModel();
dtm.setRowCount(0);
    for (int i = 0; i < data_base.size(); i++) {
        
        Details d1=data_base.get(i);
        Vector v=new Vector();
         v.add(d1.getId());
         v.add(d1.getDeadline());
         v.add(d1.getCapacity());
         v.add(d1.getPeriod());
         v.add(d1.getArrival_time());
       
       
       dtm.addRow(v);
    }
    }//GEN-LAST:event_ENTER_buttonActionPerformed
    }
    private void NEXT_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXT_buttonActionPerformed
        ID_field.setText("");
        Capacity_field.setText("");
        Deadline_field.setText("");
        Arrival_field.setText("");
        Period_field.setText("");
        ID_field.grabFocus();
        
    }//GEN-LAST:event_NEXT_buttonActionPerformed

    private void SCHEDULE_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCHEDULE_buttonActionPerformed
      
        if(Seconds_field.getText().isEmpty()){
     JOptionPane.showMessageDialog(this,"please ennter number of seconds you want to schedule !",
                   "Error massage",JOptionPane.ERROR_MESSAGE );
        }else{
        
        int remember=-1;
        int deadline=100;
         tk = new Time_keeper();
        run ecxecute = new run();
        
        tk.setMax_time(Integer.valueOf(Seconds_field.getText()));
         
        while (tk.getTime() <= tk.getMax_time()){
            
        for (int i = 0; i < data_base.size(); i++){
            Details dt = data_base.get(i);
            int clone = dt.getDeadline();
            if(clone<deadline && dt.getArrival_time()<=tk.getTime()){
                deadline=clone;
                remember=i;
            }
            
        }
     
        if(remember==-1 ){
          
          int ftime=tk.getTime();
          tk.result[ftime]="non";
          ftime=ftime+1;
          tk.setTime(ftime);
        }
        else{
        ecxecute.schedule(data_base.get(remember),tk);
        deadline =100;
        remember=-1;
    } 
        }
    for(int s=0;s<tk.getMax_time();s++){
    System.out.println(tk.result[s]);
    }
    schedule_results rr = new schedule_results();
    rr.setVisible(true);
    
    
        }
    
    
    }//GEN-LAST:event_SCHEDULE_buttonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IScheduler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Arrival_field;
    private javax.swing.JTextField Capacity_field;
    private javax.swing.JTextField Deadline_field;
    private javax.swing.JButton ENTER_button;
    private javax.swing.JTextField ID_field;
    private javax.swing.JButton NEXT_button;
    private javax.swing.JTextField Period_field;
    private javax.swing.JButton SCHEDULE_button;
    private javax.swing.JTextField Seconds_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mytable;
    // End of variables declaration//GEN-END:variables
}
